nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: ['^http://193.168.145.227:8090$']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers: ['Content-Type', 'Authorization']
        expose_headers: ['Link']
        max_age: 3600
    paths:
        '^/api/': ~